baseurl = "/"
languageCode = "en-au"
title = "Charlotte Dawson"
theme = "kondo"
copyright = "CC BY 4.0"
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
  
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3
  
[params]
  author = "Charlotte Dawson"
  darkmodetoggle = true
  gototop = true
  footer = "[Home](/) [License](/license/) [Source](https://github.com/csdaw/kondo-example)"

[markup]
  [markup.highlight]
    noclasses = false
  [markup.goldmark.renderer]
    unsafe = true
