baseurl = "/"
languageCode = "en-au"
title = "This is the title"
theme = "kondo"
copyright = "CC BY 4.0"
pluralizelisttitles = false

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
  
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3
  
[params]
  author = "Charlotte Dawson"
